name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Create a build directory
        run: mkdir build

      - name: Copy files to build directory
      run: rsync -av --exclude 'build' ./ build/  # Copy all files to the build directory, adjust if necessary

      - name: Inject API key into JavaScript
        run: |
          echo "export const joinClub = {\nBASE_URL: "https://script.google.com/macros/s",\nAPI_KEY: ${{secrets.JOINCLUB}},\n};\nexport const team = {\nBASE_URL: "https://script.google.com/macros/s",\nAPI_KEY: ${{secrets.TEAM}},\n};\nexport const event = {\nBASE_URL: "https://script.google.com/macros/s",\nAPI_KEY: ${{secrets.EVENT}},\n\n};" >> build/src/js/config.js  # Create config.js with the API key

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Directory to publish
